src/ExampleWebshop.UI.Web/ViewModels/CartViewModel.cs
using ExampleWebshop.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleWebshop.UI.Web
{
    public class CartViewModel
    {
        public int ItemId { get; set; }
        public int Quantity { get; set; }
    }
}

src/ExampleWebshop.UI.Web/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleWebshop.UI.Web
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }

    public class SignupViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StreetName { get; set; }
        public string HouseNumber { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ReturnUrl { get; set; }
    }
}

src/ExampleWebshop.UI.Web/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExampleWebshop.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebshop.UI.Web.Pages
{
    public class CartModel : PageModel
    {
        private readonly ICatalog catalog;
        public ICart Cart;

        [BindProperty]
        public CartViewModel CartViewModel { get; set; }

        public CartModel(IHttpContextAccessor httpContextAccessor, ICatalog catalog)
        {
            Cart = httpContextAccessor.HttpContext.GetCart();
            this.catalog = catalog;
        }

        public void OnGet()
        {

        }

        public void OnPost()
        {
            var item = catalog.Get(CartViewModel.ItemId);
            Cart.AddItem(item, CartViewModel.Quantity);
        }

        public void OnPostDelete()
        {
            var item = catalog.Get(CartViewModel.ItemId);
            Cart.RemoveItem(item, CartViewModel.Quantity);
        }

        public void OnPostQuantity()
        {
            var item = catalog.Get(CartViewModel.ItemId);
            
            if(CartViewModel.Quantity >= 0)
            {
                Cart.AddItem(item);
            }
            else
            {
                Cart.RemoveItem(item);
            }
        }

        public void OnPostClear()
        {
            Cart.Clear();
        }
    }
}

src/ExampleWebshop.UI.Web/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExampleWebshop.Core;
using ExampleWebshop.UI.Web.Users;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebshop.UI.Web.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly UserStore userStore;
        private readonly ICheckoutService checkoutService;

        public ICart Cart { get; set; }
        public Person Person { get; set; }

        public CheckoutModel(UserStore userStore, ICheckoutService checkoutService)
        {
            this.userStore = userStore;
            this.checkoutService = checkoutService;
        }

        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            if (!context.HttpContext.IsLoggedIn())
            {
                context.Result = new RedirectResult("/login?returnUrl=Checkout");
            }
            else
            {
                Initialize();
            }
            
            base.OnPageHandlerExecuting(context);
        }

        private void Initialize()
        {
            Cart = HttpContext.GetCart();
            Person = userStore.GetPerson(HttpContext.Session.GetString("email"));
        }

        public IActionResult OnPost()
        {
            checkoutService.Checkout(Cart, Person);
            return RedirectToPage("PostCheckout");
        }
    }
}

src/ExampleWebshop.UI.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebshop.UI.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/ExampleWebshop.UI.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExampleWebshop.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebshop.UI.Web.Pages
{
    public class IndexModel : PageModel
    {
        public readonly ICatalog Catalog;

        public IndexModel(ICatalog catalog)
        {
            this.Catalog = catalog;
        }

        public void OnGet()
        {
        }
    }
}

src/ExampleWebshop.UI.Web/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ExampleWebshop.Core;
using ExampleWebshop.UI.Web.Users;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebshop.UI.Web.Pages
{
    public class LoginModel : PageModel
    {
        public string ReturnUrl = "";
        public string LoginError = string.Empty;
        public string SignupError = string.Empty;

        private readonly UserStore userStore;

        [BindProperty]
        public LoginViewModel LoginViewModel { get; set; }

        [BindProperty]
        public SignupViewModel SignupViewModel { get; set; }

        public LoginModel(IHttpContextAccessor httpContextAccessor, UserStore userStore)
        {
            ReturnUrl = httpContextAccessor.HttpContext.Request.Headers["Referer"];

            if (httpContextAccessor.HttpContext.Request.Query.Keys.Contains("returnUrl"))
            {
                ReturnUrl = httpContextAccessor.HttpContext.Request.Query["returnUrl"].ToString();
            }

            this.userStore = userStore;
        }

        public IActionResult OnPost()
        {
            if(userStore.Validate(LoginViewModel.Email, LoginViewModel.Password))
            {
                return Login(LoginViewModel.Email, LoginViewModel.ReturnUrl);   
            }
            else
            {
                LoginError = "Invalid username or password.";
                return new PageResult();
            }
        }

        public IActionResult OnPostSignup()
        {
            var person = new Person
            {
                Email = SignupViewModel.Email,
                FirstName = SignupViewModel.FirstName,
                LastName = SignupViewModel.LastName,
                AddressLine1 = $"{SignupViewModel.StreetName} {SignupViewModel.HouseNumber}",
                AddressLine2 = $"{SignupViewModel.PostalCode} {SignupViewModel.City}",
                AddressLine3 = SignupViewModel.Country
            };

            if(!userStore.Register(person, SignupViewModel.Password))
            {
                SignupError = "The user already exists, please use different e-mail address.";
                return new PageResult();
            }

            return Login(person.Email, SignupViewModel.ReturnUrl);
        }

        public IActionResult OnPostLogout()
        {
            return Logout();
        }

        private IActionResult Login(string email, string returnUrl)
        {
            HttpContext.Session.SetString("email", email);
            return Redirect(returnUrl);
        }

        private IActionResult Logout()
        {
            HttpContext.Session.Remove("email");
            return Redirect("/");
        }
    }
}

src/ExampleWebshop.UI.Web/Pages/PostCheckout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebshop.UI.Web.Pages
{
    public class PostCheckoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/ExampleWebshop.UI.Web/Pages/Cart.cshtml
@page
@model ExampleWebshop.UI.Web.Pages.CartModel
@{
    ViewData["Title"] = "Cart";
}

<style>
    .table td {
        vertical-align: middle;
    }

        .table td img {
            border-radius: 4px;
        }

        .table td:first-child {
            width: 64px;
        }

        .table td:last-child {
            width: 24px;
        }
</style>

<h1 class="float-left">Cart</h1>

<form method="post" asp-page-handler="clear">
    <input type="submit" class="btn btn-outline-danger float-right" value="Clear cart" />
</form>

<div class="clearfix"></div>
<hr />

@if (Model.Cart.Items().Count() > 0)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cart.Items())
            {
                <tr>
                    <td>
                        <img src="https://picsum.photos/64?__@item.Key.Name" alt="@item.Key.Name.">
                    </td>
                    <td>
                        <p>
                            @item.Key.Name
                        </p>
                    </td>
                    <td>
                        <div class="row">
                            <div class="col-6">
                                <p>
                                    @item.Value
                                </p>
                            </div>
                            <div class="col-3">
                                <form asp-page-handler="quantity" method="post">
                                    @Html.AntiForgeryToken()
                                    <input type="hidden" name="ItemId" value="@item.Key.Id" />
                                    <input type="hidden" name="Quantity" value="-1" />
                                    <input type="submit" class="btn btn-outline-danger" value="-" />
                                </form>
                            </div>
                            <div class="col-3">
                                <form asp-page-handler="quantity" method="post">
                                    @Html.AntiForgeryToken()
                                    <input type="hidden" name="ItemId" value="@item.Key.Id" />
                                    <input type="hidden" name="Quantity" value="1" />
                                    <input type="submit" class="btn btn-outline-success" value="+" />
                                </form>
                            </div>
                        </div>
                    </td>
                    <td class="text-right">
                        <p>
                            $@item.Key.Price
                        </p>
                    </td>
                    <td class="text-right">
                        <p>
                            $@(item.Key.Price * item.Value)
                        </p>
                    </td>
                    <td>
                        <form asp-page-handler="delete" method="post">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="ItemId" value="@item.Key.Id" />
                            <input type="hidden" name="Quantity" value="@item.Value" />
                            <input type="submit" class="btn btn-outline-danger" value="X" />
                        </form>


                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" class="text-right">Total: <strong>$@Model.Cart.CalculateTotal()</strong></td>
                <td></td>
            </tr>
        </tfoot>
    </table>


    <a href="/Checkout" class="btn btn-primary">Checkout</a>
}
else
{
    <div class="text-center">
        <img style="width: 512px; opacity: .33" src="https://cdn.dribbble.com/users/1244867/screenshots/4346888/empty_cart.jpg" />
        <p class="lead">You have no items in your cart.</p>
        <hr class="my-4">
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="/" role="button">Browse the catalog</a>
        </p>
    </div>
}

src/ExampleWebshop.UI.Web/Pages/Checkout.cshtml
@page
@model ExampleWebshop.UI.Web.Pages.CheckoutModel
@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>

<p>Please validate your order and address details below.</p>

<h2>Address details</h2>
<table class="table table-bordered">
    <thead></thead>
    <tbody>
        <tr>
            <td>
                <strong>Full name</strong>
            </td>
            <td>
                @Model.Person.FirstName @Model.Person.LastName
            </td>
        </tr>
        <tr>
            <td>
                <b>Address</b>
            </td>
            <td>
                <p>@Model.Person.AddressLine1</p>
                <p>@Model.Person.AddressLine2</p>
                <p>@Model.Person.AddressLine3</p>
            </td>
        </tr>
    </tbody>
</table>

<hr/>

<h2>Order details</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cart.Items())
        {
            <tr>
                <td>
                    <img src="https://picsum.photos/64?__@item.Key.Name" alt="@item.Key.Name.">
                </td>
                <td>
                    <p>
                        @item.Key.Name
                    </p>
                </td>
                <td>
                    <div class="row">
                        <p>
                            @item.Value
                        </p>
                    </div>
                </td>
                <td class="text-right">
                    <p>
                        $@item.Key.Price
                    </p>
                </td>
                <td class="text-right">
                    <p>
                        $@(item.Key.Price * item.Value)
                    </p>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" class="text-right">
                <h4>Total: <strong>$@Model.Cart.CalculateTotal()</strong></h4>
            </td>
        </tr>
    </tfoot>
</table>

<hr/>

<h2>Payment</h2>

<div class="d-block my-3">
    <div class="custom-control custom-radio">
        <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
        <label class="custom-control-label" for="credit">Credit card</label>
    </div>
    <div class="custom-control custom-radio">
        <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required="">
        <label class="custom-control-label" for="debit">Debit card</label>
    </div>
    <div class="custom-control custom-radio">
        <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required="">
        <label class="custom-control-label" for="paypal">Paypal</label>
    </div>
</div>

<hr/>


<form method="post">
    <input type="submit" class="btn btn-primary" value="Confirm order" />
</form>

src/ExampleWebshop.UI.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="row">
        <div class="card-columns">
            @foreach (var item in Model.Catalog.All())
            {
                <div class="card anim-fade-in" style="width: 18rem;">
                    <img class="card-img-top anim-fade-in" style="height: 162px" src="https://picsum.photos/288/162?@item.Name" alt="@item.Name.">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">@item.Description</p>
                        <form method="post" action="/Cart">
                            @Html.AntiForgeryToken()

                            <input type="hidden" name="ItemId" value="@item.Id" />
                            <div class="row">
                                <div class="col-6">
                                    <input type="number" class="form-control" name="Quantity" min="1" max="99" value="1" />
                                </div>
                                <div class="col-6 text-right">
                                    <input type="submit" class="btn btn-outline-primary" value="Add" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            }

        </div>


    </div>

@*<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.Catalog.All())
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Price
                </td>
                <td>
                    
                </td>
            </tr>
        }
    </tbody>
</table>*@

src/ExampleWebshop.UI.Web/Pages/Login.cshtml
@page
@model ExampleWebshop.UI.Web.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}


<div class="row">
    <div class="col-6">
        <h2>Login</h2>

        <form method="post">
            <div class="form-group">
                <label>Email address</label>
                <input type="email" name="email" class="form-control" required placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll sometimes share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" required name="password" placeholder="Password">
            </div>

            @if(!string.IsNullOrWhiteSpace(Model.LoginError))
            {
                <div class="alert alert-danger">@Model.LoginError</div>
            }

            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
    
    <div class="col-6">
        <h2>Signup</h2>

        <form class="needs-validation" method="post" asp-page-handler="signup" novalidate>

            <div class="mb-3">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="you@example.com">
                <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                </div>
            </div>

            <div class="mb-3">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
                <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                </div>
            </div>

            <hr class="mb-4">

            <h4 class="mb-3">Account details</h4>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">First name</label>
                    <input type="text" class="form-control" name="firstName" id="firstName" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Valid first name is required.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="lastName">Last name</label>
                    <input type="text" class="form-control" id="lastName" name="lastName" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Valid last name is required.
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 mb-3">
                    <label for="streetName">Street</label>
                    <input type="text" class="form-control" name="streetName" id="streetName" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Valid street name is required.
                    </div>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="houseNumber">House number</label>
                    <input type="text" class="form-control" id="houseNumber" name="houseNumber" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Valid house number is required.
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="postalCode">Postal code</label>
                    <input type="text" class="form-control" name="postalCode" id="postalCode" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Valid postal code is required.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="city">City</label>
                    <input type="text" class="form-control" id="city" name="city" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Valid city is required.
                    </div>
                </div>
            </div>

            <div>
                <label for="country">Country</label>
                <select class="custom-select d-block w-100" id="country" name="country" required>
                    <option value="">Choose...</option>
                    <option>Netherlands</option>
                    <option>Belgium</option>
                    <option>Germany</option>
                </select>
                <div class="invalid-feedback">
                    Please select a valid country.
                </div>
            </div>

            <hr class="mb-4">

            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />

            @if(!string.IsNullOrWhiteSpace(Model.SignupError))
            {
                <div class="alert alert-danger">@Model.SignupError</div>
            }

            <input type="submit" class="btn btn-primary" value="Create account" />

        </form>

    </div>

</div>

src/ExampleWebshop.UI.Web/Pages/PostCheckout.cshtml
@page
@model ExampleWebshop.UI.Web.Pages.PostCheckoutModel
@{
    ViewData["Title"] = "PostCheckout";
}

<div class="text-center">
    <h1 class="display-4">Thank you!</h1>
    <img src="https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2F5GoVLqeAOo6PK%2F200.gif&f=1" style="padding: 12px 0;" />
    <p class="lead">Your order will be deliverd to you door as soon as possible!</p>
    <hr class="my-4">
    <p class="lead">
        <a href="/" class="btn btn-primary">Continue shopping</a>
    </p>
</div>

src/ExampleWebshop.UI.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Example Webshop</title>

    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
        </environment>*@
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Example Webshop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cart">
                                Cart
                            </a>
                        </li>
                    </ul>


                </div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @if (Context.IsLoggedIn())
                        {
                            <form method="post" asp-page="login" asp-page-handler="logout">
                                <input type="submit" value="Logout" class="btn btn-outline-secondary"/>
                            </form>     
                        }
                        else
                        {
                            <a href="/Login" class="btn btn-outline-secondary">Login</a>
                        }
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; @DateTime.Now.Year - Example Webshop
            </div>
        </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>